[package]
name = "generated_app"
version = "0.1.0"
edition = "2021"

[build-dependencies]
handlebars = "6.3"
serde = { version = "1.0", features = ["derive"] } # Add the "derive" feature
once_cell = "1.18.0"
